<template>
  <h1 class="title has-text-centered mt-3">PRIVACY & SECURITY POLICY</h1>
  <hr class="divider"/>
  <div class="privacy">
    
    <h2 class="subtitle is-uppercase">PRIVACY POLICY</h2>
    <p class="block">This is an official U.S. Army website, and is provided as a public service by Army Public Affairs.</p>
    <p class="block">Information presented on Army.mil is considered public information and may be distributed or copied unless otherwise specified. Use of appropriate byline/photo/image credits is requested.</p>
    <p class="block">Privacy Act Statement - If you choose to provide us with personal information - like filling out a Contact Us form with e-mail and/or postal addresses - we only use that information to respond to your message or request. We will only share the information you give us with another government agency if your inquiry relates to that agency, or as otherwise required by law. We never create individual profiles or give it to any private organizations. Army.mil never collects information for commercial marketing. While you must provide an e-mail address or postal address for a response other than those generated automatically in response to questions or comments that you may submit, we recommend that you NOT include any other personal information, especially Social Security numbers. The Social Security Administration offers additional guidance on sharing your Social Security number.</p>
    <p class="block">For site management, information is collected for statistical purposes only. This government computer system uses software programs to create summary statistics, which are used for such purposes as assessing what information is of most and least interest, determining technical design specifications, and identifying system performance or problem areas.</p>
    <p>For site security purposes and to ensure that this service remains available to all users, this government computer system employs software programs to monitor network traffic to identify unauthorized attempts to upload or change information, or otherwise cause damage.</p>
    <p class="block">Except for authorized law enforcement investigations, no other attempts are made to identify individual users or their usage habits. Raw data logs are used for no other purposes and are scheduled for regular destruction in accordance with National Archives and Records Administration guidelines.</p>
    <p class="block">Unauthorized attempts to upload information or change information on this service are strictly prohibited and may be punishable under the Computer Fraud and Abuse Act of 1986, Identity Theft Enforcement and Restitution Act of 2008, and the National Information Infrastructure Protection Act.</p>

    <h2 class="subtitle is-uppercase mt-3">USE OF MEASUREMENT AND CUSTOMIZATION OF TECHNOLOGY</h2>
    <p class="block">When you visit a page on Army.mil, the internet browser on your computer may download a small file (commonly called a "cookie") so that our website can recognize your computer when you use Army.mil in the future. Army.mil uses first-party cookies to report on visitor interactions. These cookies are used to store non-personally identifiable information. Browsers do not share first-party cookies across domains. The U.S. Army does not use the information associated with cookies to track individual user activity on the Internet outside Army websites, nor does it share the data obtained through such technologies, without the user's explicit consent, with other departments or agencies. The Department of the Army does not keep a database of information obtained from the use of cookies.</p>
    <p class="block">Cookies are enabled by default to optimize website functionality and customize user experience, but users can choose not to accept the use of these cookies by changing the settings on their local computer's web browser. The USA.gov website, <a href='https://www.usa.gov/optout-instructions' target='_blank'>https://www.usa.gov/optout-instructions</a>, provides general instructions on how to opt out of cookies and other commonly used web measurement and customization technologies. Opting out of cookies still permits users to access comparable information and services; however, it may take longer to navigate or interact with the website if a user is required to fill out certain information repeatedly.</p>
  
    <h2 class="subtitle is-uppercase mt-3">SPECIFIC TECHNOLOGIES/VENDORS</h2>
    <p class="block">YouTube is utilized by this website for video delivery. For more details, please review <a href='https://www.youtube.com/t/terms' target='_blank'>YouTube Terms of Service</a> and <a href='https://policies.google.com/privacy' target='_blank'>Google Privacy Policy</a>. Akamai is utilized by this website for content delivery. For more details, please review <a href='https://www.akamai.com/us/en/privacy-policies/' target='_blank'>Akamai Terms & Conditions</a>. Google Analytics is utilized by this website. For more details, please review <a href='https://marketingplatform.google.com/about/analytics/terms/us/' target='_blank'>Google Analytics Terms of Service</a>. The U.S. Army does not gather, request, record, require, collect or track any internet users' personally identifiable information through these processes.</p>
    <p class="block">Client side opt-out mechanisms allow the user to opt out of web measurement and customization technologies by changing the settings of a specific application or program on the user's local computer. For example, users may be able to disable persistent cookies by changing the settings on commonly used web browsers. For general instructions on how to opt out of some of the most commonly used web measurements and customization technologies, go to <a href='https://www.usa.gov/optout-instructions' target='_blank'>https://www.usa.gov/optout-instructions</a>.</p>

    <h2 class="subtitle is-uppercase">USE OF THIRD-PARTY WEBSITES AND APPLICATIONS</h2>
    <p class="block">Third-party websites and applications that are not owned, operated, or controlled by the Department of Defense are integral to Internet-based operations across the Department of Defense and used to augment official communication. These capabilities include, but are not limited to, networking services, media sharing services, wikis and data mashups. A list of the Defense Department's authorized pages and uses of these services is listed at <a href='https://www.defense.gov/Resources/Military-Departments/DOD-Websites' target='_blank'>https://www.defense.gov/Resources/Military-Departments/DOD-Websites</a>. These sites may collect PII and may make it available to the Department of Defense and other users; however, the PII is not collected on behalf of, nor is it provided specifically for, the Department of Defense. The Department of Defense does not harvest and additionally collect, maintain, share or otherwise use such PII for any purpose other than that for which it is made available to all users.</p>
    <p class="block">If you have any questions or comments about the information presented here, please forward them to <a href='mailto:amy.r.cate.civ@army.mil' target='_blank'>DAC's website representative</a>.</p>
  </div>
  </template>